### ISSUE TITLE
Everytime I revert to launch or VAB a new IR button shows up in the top toolbar

### ISSUE THREAD

**Issue by drakaar** [MagicSmokeIndustries/InfernalRobotics#40]
See attached
![untitled](https://cloud.githubusercontent.com/assets/1874339/7393604/aaf8d546-ee43-11e4-89c4-6b565b03f8ee.jpg)

**Comment by ZiwKerman** [comment]
Is it with the latest 0.21.1 hotfix?

**Comment by drakaar** [comment]
I'm using CKAN

**Comment by ZiwKerman** [comment]
ok, we need to push the update there as well.
Thank you for informing us.

**Comment by drakaar** [comment]
Will it be updated soon?

**Comment by LaylBongers** [comment]
Currently this is still happening on the CKAN release, when is the update coming?

**Comment by erendrake** [comment]
@LaylConway predictions are hard, especially about the future.

**Comment by drakar** [comment]
No need to be so flippant.  

I don't know anything about CKAN so it may be very time consuming to load on there. It may be that the team would like to test it more before putting it on CKAN. It may be that other fixes are planned before deploying to CKAN.

I think the fans of this plugin (like myself) are just curious if a hotfix exists why not upload it to CKAN as soon as it's available?

**Comment by ZiwKerman** [comment]
If all goes as planned it will be happen in several hours. Only one person
can push updates and we're waiting for him.

On Mon, May 4, 2015 at 6:49 PM, Aaron Drake notifications@github.com
wrote:

> No need to be so flippant.
> 
> I don't know anything about CKAN so it may be very time consuming to load
> on there. It may be that the team would like to test it more before putting
> it on CKAN. It may be that other fixes are planned before deploying to CKAN.
> 
> I think the fans of this plugin (like myself) are just curious if a hotfix
> exists why not upload it to CKAN as soon as it's available?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MagicSmokeIndustries/InfernalRobotics/issues/40#issuecomment-98795343
> .

## 

Best regards,
Stepan Andreev

**Comment by dbent** [comment]
> I think the fans of this plugin (like myself) are just curious if a hotfix exists why not upload it to CKAN as soon as it's available?

Nothing is uploaded to CKAN, CKAN is just a repository of machine-readable installation instructions.

Anyway, the 0.21.1 metadata [already exists in CKAN](https://github.com/KSP-CKAN/CKAN-meta/tree/master/InfernalRobotics) but is not currently offered because of an issue with the way version comparisons are done to determine which is the latest. Basically 0.21 had a version number of `v0.21` and 0.21.1 has a version number of `0.21.1`. The leading `v` is treated as part of the version number and therefore `v0.21` is treated as being _newer_ than `0.21.1`.

Since Infernal Robotics metadata is indexed from Kerbal Stuff, a hacky workaround is to simply add the leading `v` to the version number on Kerbal Stuff, similar to what was done with TweakScale: KSP-CKAN/CKAN-support#125

**Comment by drakar** [comment]
Wow, sounds complicated! No wonder its not up there yet. Hopefully all the kinks will be worked out soon and the version numbers updated. 

Thanks for the info!

**Comment by ZiwKerman** [comment]
CKAN has been updated with the latest version finally, this can be closed.
